import { type NextPage } from "next";
import Head from "next/head";

import { SITE_TITLE } from "@/config";
import Login from "./Login";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>{SITE_TITLE("Home")}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            CityRays
          </h1>
          <div className="flex flex-col items-center gap-2">
            <Login />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
