import { SITE_TITLE } from "@/config";
import React from "react";
import Head from "next/head";

interface IProps {
  children: React.ReactNode;
  pageTitle: string;
}

export const Layout = ({ children, pageTitle }: IProps) => {
  return (
    <>
      <Head>
        <title>{SITE_TITLE(pageTitle)}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        {children}
      </main>
    </>
  );
};
