name: Vercel Preview Deployment
env:
  # only the vercel token should be added to the github secrets
  # all the other env variables are fetched from the vercel config
  SKIP_ENV_VALIDATION: true
on:
  push:
    branches-ignore:
      - master
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        # this pulls the relevant environment variables from the project settings in Vercel
        # and creates a .env.preview.local file with the relevant variables
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
